// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaEGiru49mSapweB8e9E6gb61eFqckV9g',
    appId: '1:442294901215:web:f9408b23decf7edb140c6a',
    messagingSenderId: '442294901215',
    projectId: 'wifi-manager-test-9cd89',
    authDomain: 'wifi-manager-test-9cd89.firebaseapp.com',
    databaseURL: 'https://wifi-manager-test-9cd89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wifi-manager-test-9cd89.appspot.com',
    measurementId: 'G-G8F1QDYFFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzwEapOK4oXe5O9rZ7RzTspETULfo6z0g',
    appId: '1:442294901215:android:cf85112d6af3976f140c6a',
    messagingSenderId: '442294901215',
    projectId: 'wifi-manager-test-9cd89',
    databaseURL: 'https://wifi-manager-test-9cd89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wifi-manager-test-9cd89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyFkRLOVZEXlscb_SaKiN6mX6H_7lgQsM',
    appId: '1:442294901215:ios:7c606ab60a92908a140c6a',
    messagingSenderId: '442294901215',
    projectId: 'wifi-manager-test-9cd89',
    databaseURL: 'https://wifi-manager-test-9cd89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wifi-manager-test-9cd89.appspot.com',
    iosBundleId: 'com.stefanussapplication.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyFkRLOVZEXlscb_SaKiN6mX6H_7lgQsM',
    appId: '1:442294901215:ios:42eaca17edef9e12140c6a',
    messagingSenderId: '442294901215',
    projectId: 'wifi-manager-test-9cd89',
    databaseURL: 'https://wifi-manager-test-9cd89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wifi-manager-test-9cd89.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
